### ISSUE TITLE
inclusao de database

### ISSUE THREAD

**Issue by carolmkl** [carolmkl/TrabalhoBD2#1]
quando cria uma tabela ele não está jogando para o metadados, é necessário reiniciar o app pra poder fazer o select do banco.

**Comment by evandroMSchmitz** [comment]
?, Isso é facil de ser resolvido, já sei até o problema. É so recarregar todos os metadados novamente. Já vou resolver.

**Comment by evandroMSchmitz** [comment]
Isso se deve ao fato que vc criou o dictonary, sendo assim se cria uma nova tabela, mas não manda recarregar os metados dá nisso.

**Comment by evandroMSchmitz** [comment]
acho que resolvi o problema, podes testar novamente e ver se o erro continua ocorrendo?

**Comment by carolmkl** [comment]
ops
nao achei que vc estava on line. era pra nao esquecer de comentar depois

**Comment by carolmkl** [comment]
vamos ver os conflitos entao :)

**Comment by evandroMSchmitz** [comment]
eu não tava, mas recebo e-mail dos comentarios q vc faz, quase que nem no ava2, kkkk.
Vi o e-mail e fui resolver.

**Comment by carolmkl** [comment]
sincronizei o git e nao vi sua alteracao... eu tinha resolvido este por aqui tbm...

**Comment by evandroMSchmitz** [comment]
serio? estranho, mas é na na hora que dá o memoria.createTable ou Meta, depois disso é so dar um memoria.recuperarMetadados.
Vi o seu Merge, o git e seus problemas.

**Comment by evandroMSchmitz** [comment]
mas colocasse o método no lugar certo. Resolveu?

**Comment by carolmkl** [comment]
case acao.CriarTabela:
                    metadados.criarIndiciePrimary();
                    memoria.salvarMetadados(metadados);
                    memoria.recuperarMetadados(); //////SERIA ESTE que vc está falando?
                    break;

se for, não resolveria, pois ele não atualiza o metadados da memoria, mas retorna o metadados na chamada do método.

public bool salvarMetadados(Metadados meta)
        {
            try
            {
                ...
                criarTabela(meta.getNome());
                metadados.Add(meta.getNome(), meta); ///EU FIZ ISSO!!!
                return true

**Comment by evandroMSchmitz** [comment]
Certo, foi isso que eu fiz,: memoria.recuperarMetadados(); //////SERIA ESTE que vc está falando?

entendi o que vc quiz dizer, mas recomento criar um método pra fazer essa atualização do que tá na memória, isso vai ser util e necessário pros indices eu acho. Ou deixa que eu crio tanto faz

**Comment by evandroMSchmitz** [comment]
bem já fiz:
public void atualizar()
        {
            metadados = recuperarMetadados();
        }

isso tá no gerenciador de memória, bem simples não?

**Comment by carolmkl** [comment]
fechou então. :)
